<?php `git pull origin master`;
	$pull = shell_exec (" git -v pull origin master");
	$pull2 = `git pull 2>&1`;
	$who = `whoami 2>&1`;
	$date = date("D M j G:i:s T Y");
	echo "hello\n";
	echo $date;
	$File = "f.txt";
	$Handle = fopen($File, 'w');
	$Data =  $date  . "\npull " .$pull .  "\npull2: " . $pull2 . "\nWho: " . $who ;
	fwrite($Handle, $Data);
	`git pull origin master`;
	`git commit -am 'fucker'`;
	`git pull`;
